# Prática — Módulo 10 - Embeddings Semânticos (SBERT) + KMeans

In [1]:
# Carregar dados
import pandas as pd

df = pd.read_parquet("/content/df_final_1024.parquet")

print("Shape:", df.shape)

Shape: (736, 10)

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 736 entries, 0 to 735
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ClienteCod             736 non-null    int64
 1   ConteudoCategoriaNome  736 non-null    object
 2   ConteudoNome           736 non-null    object
 3   ConteudoDescricao      736 non-null    object
 4   qtd_conteudos          736 non-null    int64
 5   nome_limpo             736 non-null    object
 6   desc_limpa             736 non-null    object
 7   categorias_limpas      736 non-null    object
 8   texto_final            736 non-null    object
 9   cluster                736 non-null    int32
dtypes: int32(1), int64(2), object(7)
memory usage: 54.8+ KB

In [3]:
df.head()

,ClienteCod,ConteudoCategoriaNome,ConteudoNome,ConteudoDescricao,qtd_conteudos,nome_limpo,desc_limpa,categorias_limpas,texto_final,cluster
0,68491469,Concurso Público,Curso completo Polícia Militar de Sergipe,Curso preparatório completo em PDF e vídeo aul...,1,polícia militar sergipe,preparatório pdf vídeo aulas concurso polícia ...,[concurso público],concurso público,12
1,14400603,Vendas,Elementária - INGRESSO STANDART,"Elementária é um evento, não um curso. Um marc...",1,elementária ingresso standart,elementária evento marco empresários empresári...,[vendas],vendas,0
2,32136775,Artesanato; Empreendedorismo; Artes; Negócios ...,A MAGIA DA SABOARIA ARTESANAL (INICIANTE),A MAGIA DA SABOARIA ARTESANAL\n\nUma nova jorn...,1,magia saboaria artesanal iniciante,magia saboaria artesanal nova jornada começa a...,"[artesanato, empreendedorismo, artes, negócios...",artesanato empreendedorismo artes negócios e d...,29
3,89645602,"Saúde; Saúde, dieta e beleza",Como diminuir seu colesterol,?? Produto: eBook – Como Diminuir o Colesterol...,1,diminuir colesterol,produto diminuir colesterol naturalmente trans...,"[saúde, saúde, dieta e beleza]","saúde saúde, dieta e beleza",1
4,94688887,"Marketing; Vendas; Software, TI e Internet; We...","Crie GRATUITAMENTE Vídeos, Imagens e Sons que ...","Criação de Mídias que Vendem – Imagens, Vídeos...",1,crie gratuitamente vídeos imagens sons vendem ...,criação mídias vendem imagens vídeos sons pequ...,"[marketing, vendas, software, ti e internet, w...","marketing vendas software, ti e internet web d...",17

# **Fase 0 - Engenharia de Atributos**

In [4]:
# Transformar cada texto em lista de tokens
import re

def tokenize(text):
    text = str(text).lower()
    text = re.sub(r"[^a-záéíóúâêôãõç\s]", " ", text)
    return text.split()

sentences = df["texto_final"].apply(tokenize).apply(lambda x: x[:300])

# **Fase 1 - Representação SBERT**

In [5]:
# Criar campo textual único para vetorização
# Determinar qual campo textual vale manter
df["texto_final"] = (
    df["categorias_limpas"].apply(lambda x: " ".join(x))  # <- lista de palavras
    # + " " + df["nome_limpo"]
    + " " + df["desc_limpa"]
).str.strip()

In [6]:
# Treinar embeddings de palavras com Embeddings de Sentença (SBERT)
!pip install -q sentence-transformers

from sentence_transformers import SentenceTransformer

model = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")

textos = df["texto_final"]

X = model.encode(
    textos.tolist(),
    batch_size=64,
    show_progress_bar=True,
    normalize_embeddings=True
)

print("Shape:", X.shape)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/645 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/471M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/526 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.08M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/12 [00:00<?, ?it/s]

Shape: (736, 384)

# **Fase 2 - Clustering (KMeans)**

In [7]:
# Agrupar conteúdos usando KMeans
from sklearn.cluster import KMeans

k = 12

kmeans = KMeans(
    n_clusters=k,
    random_state=42,
    n_init=10
)

df["cluster"] = kmeans.fit_predict(X)

## Validação

### Silhouette Score

In [8]:
# Calcular qualidade geométrica dos clusters
from sklearn.metrics import silhouette_score

score = silhouette_score(X, df["cluster"])
print("Silhouette:", score)

Silhouette: 0.054887585

### Visualização de Clusters

In [9]:
import pandas as pd

pd.set_option("display.max_colwidth", None)

for i in sorted(df["cluster"].unique()):
    print(f"\nCluster {i}:")

    exemplos = df[df["cluster"] == i]["texto_final"]

    n = min(4, len(exemplos))
    for t in exemplos.sample(n, random_state=42):
      print(t)

Cluster 0:
coaching capacitação ingresso trabalho estudantes formação recém formados física encontros on line trabalho alavancar mentalidade empreendedora participante além disso irei ensinar metodologia baseada funcional dividida módulos diferentes final semana mês durante meses
educação física e esporte nesse receberá atendimento personalizado treinos direcionados tratar dor alívio recuperação completa nesse receberá tratamento personalizado suporte caso acompanharemos todas etapas alívio recuperação completa
educação física e esporte saúde sente dificuldades hora alongar treinos parece fazendo algo errado então book saiba executar principais alongamentos detalhada assertiva
saúde, dieta e beleza protocolo deusa sheipada mulheres desejam melhorar treinos impulsionar resultados academia alcançando corpo definido digno verdadeira deusa dicas práticas treino aliado atingir objetivos academia sentir verdadeira deusa agora atualizado nova versão traz ainda eficazes ajustes treinos dicas maximizar

Cluster 1:
área médica neste aprenderá melhores prevenir varizes caso aprenderá tratá las foco melhorar
educação pet terapia quarteto fantástico intervenções busca diferencial real currículo deseja entregar resultados únicos pacientes alunos pet terapia versão formação completa intervenções assistidas animais saa focada quarteto fantástico cães aves roedores répteis desenhado profissionais estudantes áreas saú
saúde todo ensinamento necessário deseja tratar descobrir possui lipedema saber identificar estágios dessa condição
vendas laserterapia desenvolvido capacitar profissionais saúde todas etapas atendimento laser baixa intensidade embasamento teórico fundamentos científicos passando elaboração plano terapêutico individualizado uso termo consentimento aborda protocolos aplicação seguras dicas marketing impulsionar atuação e

Cluster 2:
autoajuda e desenv. pessoal beleza e estética conquistar coragem ver medo padrão permissão existir merece sentir linda agora validação medos normal ter medo vamos juntas momento ousadia minutos mudam vê pertencimento sozinha nessa jornada
saúde medicina alternativa psicologia book regenerar cicatrizar categoria psicologia aplicada book regenerar cicatrizar prático busca autoconhecimento inteligência emocional transformar desafios oportunidades crescimento encontrará neste book fortalecer autoestima equilíbrio emocional melhorar comunicação relacionamentos metodologia vlc
vendas imersão mulheres transformação sair piloto automático reencontrar mulher deixou trás presencial profundo seguro entender repete padrões doem começar libertar conectam mente corpo emoção olhar verdade julgamentos entender prende soltar sair dali clareza força leveza viver
autoajuda e desenv. pessoal domine arte persuasão influência padrões linguagem poderosos imaginou ter capacidade influenciar pessoas palavras conquistar confiança instantânea obter melhores resultados interações persuasão influência usando padrões linguagem steve allen revela avançadas comunicação baseadas neurolinguística psi

Cluster 3:
beleza e estética aprenda tudo locs oque fazer após start oque fazer interromper jornada
vendas inauguração espaço sistêmica aline lins
design e fotografia voucher r uso loja melunins voucher enviado cupom desconto
vendas volta obs local data provisórios podem sofrer alteração cherry academy rio volta ainda especial grande voltamos rio queridíssimas bia ruas cintya bondezzan nivia santos carol capasso natalia barbosa bela flor andressa ferraz suzana araujo cheio palestras networking além coffee break incrível entrega

Cluster 4:
iniciação profissional material abrir universo oportunidade procura primeiro emprego dificuldades ingressar trabalho seguindo desse book estará empregado oportunidade
administração e negócios animações e design administração e gestão administração coaching jeito fácil ganhar dinheiro jeito rápido simples venha conhecer pequeno projeto
vendas maior melhor oratória contemporânea brasil especialista renomado requisitado todo país professor anderson góis treinou pessoas todo brasil dentre políticos senário nacional presidente ordem advogados brasil vários players nacional profissionais buscam posicionar anderson góis ceo empresa palco escol
mentoring transição carreira individual voltada profissionais desejam repensar trajetória tomar decisões estratégicas próximo carreira durante encontros trabalhamos autoconhecimento aplicado análise perfil construção direcionamento carreira foco clareza posicionamento tomada decisão consciente processo ajuda

Cluster 5:
saúde saúde, dieta e beleza produto diminuir colesterol naturalmente transforme saúde método simples acessível natural prático direto mostra reduzir colesterol eficaz através alimentação movimento pequenas mudanças medicamentos caros dietas restritivas sofrimento encontrar neste explicação clara colesterol tipos ldl hdl vldl a
saúde jejum intermitente adapte jejum idade volte emagrecer após anos corpo muda metabolismo desacelera hormônios oscilam métodos funcionavam antes podem parar dar mostra ajustar jejum intermitente fase radicalismo sofrimento aqui aprende quais mudanças simples fazem toda diferença continuar emagrecendo s
saúde saúde, dieta e beleza perda de peso qualidade gestão da qualidade claro aqui resumo direto prático pra emagrecer vez coma comida verdade evite industrializados açúcar farinha prefira legumes frutas proteínas gorduras boas mexa corpo todos pode caminhada treino casa dança importante movimentar durma bem sono ajuda controle fome metabolismo cuide mente ansiedade com
saúde, dieta e beleza quer emagrecer aguenta dietas restritivas desafio jejum intermitente iniciantes criado pessoas comuns rotina corrida querem emagrecer simples passar fome complicação aprender fazer jejum intermitente jeito certo protocolo ideal iniciantes comer emagrecer sofrer manter constância evitar desistência i

Cluster 6:
cotidiano desenvolvimento pessoal autoajuda e desenv. pessoal espiritualidade aqui acaso frase apenas título deste livro chamado convite despertar espiritual lembrete deus continua falando guiando redirecionando vidas amor propósito aqui acaso pedro paulo oliveira compartilha reflexões profundas nascem própria jornada pai juiz marido filho amigo homem fé capítulo revela exper
espiritualidade mistérios revelados bíblia volume nefilins gigantes anjos caídos neste primeiro volume coleção mistérios revelados bíblia leitor convidado mergulhar temas misteriosos escrituras nefilins mencionados breve porém impactante texto bíblico seres despertam perguntas atravessam séculos continuam alimentan
evangélico fortalecer conexão emocional espiritual todas fases casamento book voltado casais tema linguagem aliança sob ótica presbiteriana foca aplicação teologia aliança cotidiano matrimonial enquanto contratos visam satisfação mútua sob condições aliança presbiteriana vista vínculo sagrado incondicional dia
católico evangélico espiritualidade descubra profunda conexão israel fé cristã neste book inspirador revelador israel bíblia terra escolhida planos deus conduz jornada espiritual através promessas profecias milagres envolvem povo terra israel abordagem clara fundamentada escrituras livro traz origem israel aliança abraão libertação eg

Cluster 7:
vendas empreendedorismo investimentos educação financeira marketing digital estrutura bilionária solução completa única busca maximizar capacitação compreende diversas escalar lucrar significativamente digital ensinadas irão ajudá lo entender psicologia consumidores personalizar interação fechar oferece detalhado usar facebook ads maneira eficiente permitindo escale maneira
marketing digital estratégia através vídeos virais tiktok vamos ensinar produzir vídeos hooks chamativos viralizar tiktok vender produto através link afiliado
marketing vendas software, ti e internet web design marketing digital criação mídias vendem imagens vídeos sons pequenos negócios gratuitas criar vídeos imagens sons vendem redes pequenos negócios transforme curtidas clientes reais comece agora dono pequeno negócio quer atrair clientes redes sociais sabe onde começar prático criado especialmente ensinar produzir conte
marketing digital cuida negócio cuido presença digital gestor mídias sociais trabalho assumir responsabilidade completa redes sociais empreendedor possa focar realmente importa vender atender crescer ofereço completa estratégica personalizada incluindo criação conteúdo relevante atrativo planejamento postagens foco e

Cluster 8:
economia administração e negócios agronegócio biblioteca economia real transforme finanças estatísticas comprovadas descubra dominar economia lançar liberdade financeira book investimentos inteligentes dicas economizar modificar dinheiro oportunidades negócios acesse agora transforme relação dinheiro
vendas contadores perceberam reforma tributária particularidades contabilidade rural transformando papel contador agronegócio hoje contador especialista peça estratégica produtor rural apenas faz básico ajuda cliente crescer permanecer ano após ano cenário ainda promissor pouquíssimos contadores têm especi
finanças planilha simples entender onde dinheiro criar hábito registrar gastos começar guardar dinheiro verdade ganhando pouco
administração e negócios empreendedorismo prenda ganhar dinheiro simples acessível apenas r mãos direto ponto transformar rotina renda extra real consistente comece agora

Cluster 9:
educação crescendo juntos habilidades parentais perguntou ajudar filho lidar desafios diários aprender perder estabelecer limites saudáveis equilibrar uso tecnologia crescendo juntos habilidades parentais criado especialmente pais desejam transformar relação filhos construir ambiente familiar harmônico posit
autoajuda e desenv. pessoal sessão individual guiada acompanhamento meses vício cigarro apenas físico profundamente ligado padrões emocionais programações inconscientes mantêm ciclo ativo protocolo libertação vício realizado formato terapêutico tradicional valor médio r abrindo número limitado vagas especial supervisionado ond
saúde esgotamento coisa adulto crianças sofrendo silêncio telas excesso tarefas pressões familiares revela sinais burnout infantil ensina restaurar equilíbrio emocional saúde mental vínculo afetivo casa aprenda práticas emocional rotina saudável reconexão pais filhos ideal famílias educadores profissionai
vendas aprenda aplicar food chaining raciocínio clínico estruturado critérios progressão manejo emocional criança família seletividade alimentar queixas frequentes desafiadoras clínica pediátrica falta ausência raciocínio estruturado critérios claros progressão respeitem perfil sensorial criança contexto f

Cluster 10:
educação financeira organize finanças leve divertida eficiente planilha temática inspirada filme divertidamente perfeita deseja controlar gastos definir metas acompanhar evolução financeira mês mês recebe começar usar planilha facilidade arquivo fonte personalizada manter visual criativo único planilha finanças pessoai
marketing administração e negócios desenvolvimento pessoal empreendedorismo administração e gestão educação financeira marketing digital educção x alfabetização financeira hung park yoong difere alfabetização financeira financeira indivíduos aplicar bem conhecimentos obtidos gerar maior facilidade tomada decisão sob risco escolhas financeiras eficientes financeira proporciona compreensão respeito valor real dinheiro gerir despesas pr
finanças educação financeira consultoria start acompanhamento individual comigo duração mês voltado mulheres desejam dar primeiro organizar finanças assumir controle próprio dinheiro durante acompanhamento realizados diagnóstico financeiro preparei prático simples fazer levantamento situação financeira atual possa entender fund
educação financeira financeira completa composta cinco sessões mentorias individuais casal grupo durante seis meses via chamada vídeo podendo zoom google meet escolha contratada sessões duração aproximadamente hora podendo durar menos acordo demanda sessão ilimitado whatsapp contratada tirar dúvidas

Cluster 11:
educação acontece criança acostuma deixar tudo neste book filho acompanhar história personagem encantador enfrenta desafio comum infância preguiça através fábula envolvente descobrirá existe força interior capaz transformar rotina aprenderá ativá la força nome revelada dentro história além leitura book ofere
mentoring especializado preparação concursos policiais cronogramas detalhados aulas estratégicas aprovação
idiomas educação dualfluency premium treino compreensão auditiva brasileiros estudaram inglês ainda travam inglês acontece velocidade real cenas contextualizadas trechos guiados apoio en pt sincronizado aluno treina ouvido progressiva acompanhar melhor inglês uso real produto oferece área premium estudo trechos modo
concurso público preparatório pdf vídeo aulas concurso polícia militar estado sergipe

In [10]:
# Ver exemplos de separação
import pandas as pd

pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_rows", None)

display(
    df.groupby("cluster")["texto_final"]
    .apply(lambda x: x.sample(min(len(x), 4), random_state=42))
)

cluster
0        163                                                                                                                                                                            coaching capacitação ingresso trabalho estudantes formação recém formados física encontros on line trabalho alavancar mentalidade empreendedora participante além disso irei ensinar metodologia baseada funcional dividida módulos diferentes final semana mês durante meses
         691                                                                                                                                                                                                              educação física e esporte nesse receberá atendimento personalizado treinos direcionados tratar dor alívio recuperação completa nesse receberá tratamento personalizado suporte caso acompanharemos todas etapas alívio recuperação completa
         715                                                                                                                                                                                                                                                                                 educação física e esporte saúde sente dificuldades hora alongar treinos parece fazendo algo errado então book saiba executar principais alongamentos detalhada assertiva
         689                                                                                                                       saúde, dieta e beleza protocolo deusa sheipada mulheres desejam melhorar treinos impulsionar resultados academia alcançando corpo definido digno verdadeira deusa dicas práticas treino aliado atingir objetivos academia sentir verdadeira deusa agora atualizado nova versão traz ainda eficazes ajustes treinos dicas maximizar
1        453                                                                                                                                                                                                                                                                                                                                                             área médica neste aprenderá melhores prevenir varizes caso aprenderá tratá las foco melhorar
         641                                                                                                                                    educação pet terapia quarteto fantástico intervenções busca diferencial real currículo deseja entregar resultados únicos pacientes alunos pet terapia versão formação completa intervenções assistidas animais saa focada quarteto fantástico cães aves roedores répteis desenhado profissionais estudantes áreas saú
         419                                                                                                                                                                                                                                                                                                                                      saúde todo ensinamento necessário deseja tratar descobrir possui lipedema saber identificar estágios dessa condição
         670                                                                                                                                      vendas laserterapia desenvolvido capacitar profissionais saúde todas etapas atendimento laser baixa intensidade embasamento teórico fundamentos científicos passando elaboração plano terapêutico individualizado uso termo consentimento aborda protocolos aplicação seguras dicas marketing impulsionar atuação e
2        292                                                                                                                                                                                                           autoajuda e desenv. pessoal beleza e estética conquistar coragem ver medo padrão permissão existir merece sentir linda agora validação medos normal ter medo vamos juntas momento ousadia minutos mudam vê pertencimento sozinha nessa jornada
         6                                                                                                         saúde medicina alternativa psicologia book regenerar cicatrizar categoria psicologia aplicada book regenerar cicatrizar prático busca autoconhecimento inteligência emocional transformar desafios oportunidades crescimento encontrará neste book fortalecer autoestima equilíbrio emocional melhorar comunicação relacionamentos metodologia vlc
         293                                                                                                                                                                   vendas imersão mulheres transformação sair piloto automático reencontrar mulher deixou trás presencial profundo seguro entender repete padrões doem começar libertar conectam mente corpo emoção olhar verdade julgamentos entender prende soltar sair dali clareza força leveza viver
         109                                                                                                                 autoajuda e desenv. pessoal domine arte persuasão influência padrões linguagem poderosos imaginou ter capacidade influenciar pessoas palavras conquistar confiança instantânea obter melhores resultados interações persuasão influência usando padrões linguagem steve allen revela avançadas comunicação baseadas neurolinguística psi
3        612                                                                                                                                                                                                                                                                                                                                                                 beleza e estética aprenda tudo locs oque fazer após start oque fazer interromper jornada
         593                                                                                                                                                                                                                                                                                                                                                                                                           vendas inauguração espaço sistêmica aline lins
         570                                                                                                                                                                                                                                                                                                                                                                           design e fotografia voucher r uso loja melunins voucher enviado cupom desconto
         709                                                                                                                                      vendas volta obs local data provisórios podem sofrer alteração cherry academy rio volta ainda especial grande voltamos rio queridíssimas bia ruas cintya bondezzan nivia santos carol capasso natalia barbosa bela flor andressa ferraz suzana araujo cheio palestras networking além coffee break incrível entrega
4        594                                                                                                                                                                                                                                                                                   iniciação profissional material abrir universo oportunidade procura primeiro emprego dificuldades ingressar trabalho seguindo desse book estará empregado oportunidade
         187                                                                                                                                                                                                                                                                                administração e negócios animações e design administração e gestão administração coaching jeito fácil ganhar dinheiro jeito rápido simples venha conhecer pequeno projeto
         602                                                                                                                                      vendas maior melhor oratória contemporânea brasil especialista renomado requisitado todo país professor anderson góis treinou pessoas todo brasil dentre políticos senário nacional presidente ordem advogados brasil vários players nacional profissionais buscam posicionar anderson góis ceo empresa palco escol
         609                                                                                                                                    mentoring transição carreira individual voltada profissionais desejam repensar trajetória tomar decisões estratégicas próximo carreira durante encontros trabalhamos autoconhecimento aplicado análise perfil construção direcionamento carreira foco clareza posicionamento tomada decisão consciente processo ajuda
5        3                                                                                                                   saúde saúde, dieta e beleza produto diminuir colesterol naturalmente transforme saúde método simples acessível natural prático direto mostra reduzir colesterol eficaz através alimentação movimento pequenas mudanças medicamentos caros dietas restritivas sofrimento encontrar neste explicação clara colesterol tipos ldl hdl vldl a
         65                                                                                                                                        saúde jejum intermitente adapte jejum idade volte emagrecer após anos corpo muda metabolismo desacelera hormônios oscilam métodos funcionavam antes podem parar dar mostra ajustar jejum intermitente fase radicalismo sofrimento aqui aprende quais mudanças simples fazem toda diferença continuar emagrecendo s
         462                                                                     saúde saúde, dieta e beleza perda de peso qualidade gestão da qualidade claro aqui resumo direto prático pra emagrecer vez coma comida verdade evite industrializados açúcar farinha prefira legumes frutas proteínas gorduras boas mexa corpo todos pode caminhada treino casa dança importante movimentar durma bem sono ajuda controle fome metabolismo cuide mente ansiedade com
         285                                                                                                                       saúde, dieta e beleza quer emagrecer aguenta dietas restritivas desafio jejum intermitente iniciantes criado pessoas comuns rotina corrida querem emagrecer simples passar fome complicação aprender fazer jejum intermitente jeito certo protocolo ideal iniciantes comer emagrecer sofrer manter constância evitar desistência i
6        403                                                               cotidiano desenvolvimento pessoal autoajuda e desenv. pessoal espiritualidade aqui acaso frase apenas título deste livro chamado convite despertar espiritual lembrete deus continua falando guiando redirecionando vidas amor propósito aqui acaso pedro paulo oliveira compartilha reflexões profundas nascem própria jornada pai juiz marido filho amigo homem fé capítulo revela exper
         96                                                                                                                              espiritualidade mistérios revelados bíblia volume nefilins gigantes anjos caídos neste primeiro volume coleção mistérios revelados bíblia leitor convidado mergulhar temas misteriosos escrituras nefilins mencionados breve porém impactante texto bíblico seres despertam perguntas atravessam séculos continuam alimentan
         411                                                                                                                                  evangélico fortalecer conexão emocional espiritual todas fases casamento book voltado casais tema linguagem aliança sob ótica presbiteriana foca aplicação teologia aliança cotidiano matrimonial enquanto contratos visam satisfação mútua sob condições aliança presbiteriana vista vínculo sagrado incondicional dia
         204                                                                                                         católico evangélico espiritualidade descubra profunda conexão israel fé cristã neste book inspirador revelador israel bíblia terra escolhida planos deus conduz jornada espiritual através promessas profecias milagres envolvem povo terra israel abordagem clara fundamentada escrituras livro traz origem israel aliança abraão libertação eg
7        563                                                                 vendas empreendedorismo investimentos educação financeira marketing digital estrutura bilionária solução completa única busca maximizar capacitação compreende diversas escalar lucrar significativamente digital ensinadas irão ajudá lo entender psicologia consumidores personalizar interação fechar oferece detalhado usar facebook ads maneira eficiente permitindo escale maneira
         626                                                                                                                                                                                                                                                                                           marketing digital estratégia através vídeos virais tiktok vamos ensinar produzir vídeos hooks chamativos viralizar tiktok vender produto através link afiliado
         4                                                                         marketing vendas software, ti e internet web design marketing digital criação mídias vendem imagens vídeos sons pequenos negócios gratuitas criar vídeos imagens sons vendem redes pequenos negócios transforme curtidas clientes reais comece agora dono pequeno negócio quer atrair clientes redes sociais sabe onde começar prático criado especialmente ensinar produzir conte
         486                                                                                                                           marketing digital cuida negócio cuido presença digital gestor mídias sociais trabalho assumir responsabilidade completa redes sociais empreendedor possa focar realmente importa vender atender crescer ofereço completa estratégica personalizada incluindo criação conteúdo relevante atrativo planejamento postagens foco e
8        567                                                                                                                                            economia administração e negócios agronegócio biblioteca economia real transforme finanças estatísticas comprovadas descubra dominar economia lançar liberdade financeira book investimentos inteligentes dicas economizar modificar dinheiro oportunidades negócios acesse agora transforme relação dinheiro
         307                                                                                                                                      vendas contadores perceberam reforma tributária particularidades contabilidade rural transformando papel contador agronegócio hoje contador especialista peça estratégica produtor rural apenas faz básico ajuda cliente crescer permanecer ano após ano cenário ainda promissor pouquíssimos contadores têm especi
         268                                                                                                                                                                                                                                                                                                                           finanças planilha simples entender onde dinheiro criar hábito registrar gastos começar guardar dinheiro verdade ganhando pouco
         450                                                                                                                                                                                                                                                                               administração e negócios empreendedorismo prenda ganhar dinheiro simples acessível apenas r mãos direto ponto transformar rotina renda extra real consistente comece agora
9        205                                                                                                                                    educação crescendo juntos habilidades parentais perguntou ajudar filho lidar desafios diários aprender perder estabelecer limites saudáveis equilibrar uso tecnologia crescendo juntos habilidades parentais criado especialmente pais desejam transformar relação filhos construir ambiente familiar harmônico posit
         720                                                                                                                 autoajuda e desenv. pessoal sessão individual guiada acompanhamento meses vício cigarro apenas físico profundamente ligado padrões emocionais programações inconscientes mantêm ciclo ativo protocolo libertação vício realizado formato terapêutico tradicional valor médio r abrindo número limitado vagas especial supervisionado ond
         730                                                                                                                                       saúde esgotamento coisa adulto crianças sofrendo silêncio telas excesso tarefas pressões familiares revela sinais burnout infantil ensina restaurar equilíbrio emocional saúde mental vínculo afetivo casa aprenda práticas emocional rotina saudável reconexão pais filhos ideal famílias educadores profissionai
         713                                                                                                                                      vendas aprenda aplicar food chaining raciocínio clínico estruturado critérios progressão manejo emocional criança família seletividade alimentar queixas frequentes desafiadoras clínica pediátrica falta ausência raciocínio estruturado critérios claros progressão respeitem perfil sensorial criança contexto f
10       423                                                                                                                         educação financeira organize finanças leve divertida eficiente planilha temática inspirada filme divertidamente perfeita deseja controlar gastos definir metas acompanhar evolução financeira mês mês recebe começar usar planilha facilidade arquivo fonte personalizada manter visual criativo único planilha finanças pessoai
         376    marketing administração e negócios desenvolvimento pessoal empreendedorismo administração e gestão educação financeira marketing digital educção x alfabetização financeira hung park yoong difere alfabetização financeira financeira indivíduos aplicar bem conhecimentos obtidos gerar maior facilidade tomada decisão sob risco escolhas financeiras eficientes financeira proporciona compreensão respeito valor real dinheiro gerir despesas pr
         82                                                                                                                 finanças educação financeira consultoria start acompanhamento individual comigo duração mês voltado mulheres desejam dar primeiro organizar finanças assumir controle próprio dinheiro durante acompanhamento realizados diagnóstico financeiro preparei prático simples fazer levantamento situação financeira atual possa entender fund
         596                                                                                                                                             educação financeira financeira completa composta cinco sessões mentorias individuais casal grupo durante seis meses via chamada vídeo podendo zoom google meet escolha contratada sessões duração aproximadamente hora podendo durar menos acordo demanda sessão ilimitado whatsapp contratada tirar dúvidas